---
# SPDX-FileCopyrightText: Â© 2025 Olivier Meunier <olivier@neokraft.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Get /info
routes:
  /info:
    get:
      tags: [info]
      $merge:
        - "traits.yaml#public"

      summary: Information
      description: |
        This route returns public information about the Readeck instance.

      responses:
        "200":
          description: Server information
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: object
                    properties:
                      canonical:
                        type: string
                        description: Canonical (full) version string
                      release:
                        type: string
                        description: Release version number
                      build:
                        type: string
                        description: Build number (can be empty)
                  features:
                    type: array
                    items:
                      type: string
                    description: Available features