name: Sync from Codeberg

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Mirror clone from Codeberg
        run: |
          git clone --mirror https://codeberg.org/readeck/readeck.git readeck.git
          cd readeck.git

      - name: Push branches and tags to GitHub
        env:
          TOKEN: ${{ secrets.READECK_MIRROR }}
        run: |
          cd readeck.git
          git remote add github https://${TOKEN}@github.com/${{ github.repository }}.git
          
          git push github --force 'refs/heads/*'
          
          git push github --force 'refs/tags/*'
          
          echo "âœ…"
